version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: CardsDB
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"