spring:
  datasource:
    url: jdbc:mysql://localhost:3307/CardsDB
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: false
    user: admin
    password: admin
    url: jdbc:mysql://localhost:3307/CardsDB
    locations: filesystem:db/migration
