spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CardsDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    user: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/CardsDB
    locations: filesystem:db/migration
